function u0_anchor_case_summary_demo()
% Batch summary for the anchored u0 homotopy demo cases.
%
% Runs the configured benchmark cases, collects the final diagnostics from
% each case history file, and writes a consolidated CSV/Markdown summary.

    cases = case_catalog();
    output_dir = fullfile(pwd, 'output', 'u0_anchor_case_summary');
    if ~exist(output_dir, 'dir')
        mkdir(output_dir);
    end

    num_cases = numel(cases);
    summary_rows = repmat(empty_summary_row(), num_cases, 1);

    for k = 1:num_cases
        spec = cases(k);
        fprintf('\n===== SUMMARY CASE %s =====\n', spec.case_name);
        u0_anchor_monge_ampere_homotopy_demo(spec.case_name);
        summary_rows(k) = collect_case_summary(spec);
    end

    summary_table = struct2table(summary_rows);
    writetable(summary_table, fullfile(output_dir, 'u0_anchor_case_summary.csv'));
    write_markdown_summary(summary_table, fullfile(output_dir, 'u0_anchor_case_summary.md'));

    disp(summary_table);
    fprintf('Summary written under %s\n', output_dir);
end

function cases = case_catalog()
    cases = struct( ...
        'case_name', { ...
            'paper_example_5_1', ...
            'paper_example_5_1_noexact', ...
            'quartic_convex', ...
            'scaled_quartic_convex', ...
            'mild_exp_separable', ...
            'mixed_polynomial_convex', ...
            'mild_sextic_convex', ...
            'gaussian_bump_convex', ...
            'trig_convex'}, ...
        'family', { ...
            'radial exponential', ...
            'radial exponential (no exact diagnostics)', ...
            'quartic polynomial', ...
            'scaled quartic polynomial', ...
            'separable exponential', ...
            'mixed polynomial with xy coupling', ...
            'separable sextic polynomial', ...
            'quadratic plus Gaussian bump', ...
            'trigonometric near-degenerate convex'}, ...
        'difficulty', { ...
            'easy', ...
            'easy', ...
            'medium', ...
            'medium', ...
            'easy', ...
            'easy-medium', ...
            'easy-medium', ...
            'easy-medium', ...
            'hard'}, ...
        'rhs_character', { ...
            'f >= 1, smooth positive', ...
            'f >= 1, smooth positive', ...
            'f >= 1, polynomial growth', ...
            'small positive f, polynomial growth', ...
            'small positive f, smooth separable', ...
            'f >= 1, smooth coupled polynomial', ...
            'f >= 1, smooth positive polynomial', ...
            'f > 0, smooth localized perturbation', ...
            'positive but close to zero in places'}, ...
        'solution_character', { ...
            'smooth strongly convex exact solution', ...
            'same solution, exact diagnostics disabled', ...
            'smooth polynomial convex solution', ...
            'same quartic shape with weaker curvature scale', ...
            'mild-curvature separable convex solution', ...
            'smooth convex polynomial with mixed term', ...
            'smooth sextic convex solution', ...
            'smooth strongly convex quadratic with local bump', ...
            'oscillatory convex solution near degeneracy'}, ...
        'solver_mode', { ...
            'default adaptive constrained run', ...
            'default adaptive constrained run', ...
            'default adaptive constrained run', ...
            'default adaptive constrained run', ...
            'default adaptive constrained run', ...
            'default adaptive constrained run', ...
            'default adaptive constrained run', ...
            'default adaptive constrained run', ...
            'fixed-step unconstrained stress test'} ...
    );
end

function row = empty_summary_row()
    row = struct( ...
        'CaseName', "", ...
        'Family', "", ...
        'Difficulty', "", ...
        'RHSCharacter', "", ...
        'SolutionCharacter', "", ...
        'SolverMode', "", ...
        'Success', false, ...
        'ReachedTEnd', false, ...
        'FinalT', NaN, ...
        'FinalResidualInf', NaN, ...
        'FinalGridL2', NaN, ...
        'FinalFDH1', NaN, ...
        'FinalFDH2', NaN, ...
        'FinalJacobianCond', NaN, ...
        'FinalPSDRatio', NaN, ...
        'FinalIndefRatio', NaN, ...
        'Suitability', "", ...
        'Comment', "" ...
    );
end

function row = collect_case_summary(spec)
    history_path = fullfile(pwd, 'output', ...
        ['u0_anchor_monge_ampere_homotopy_' spec.case_name], ...
        'u0_anchor_history.csv');
    history_table = readtable(history_path);
    final_row = history_table(end, :);

    row = empty_summary_row();
    row.CaseName = string(spec.case_name);
    row.Family = string(spec.family);
    row.Difficulty = string(spec.difficulty);
    row.RHSCharacter = string(spec.rhs_character);
    row.SolutionCharacter = string(spec.solution_character);
    row.SolverMode = string(spec.solver_mode);
    row.FinalT = final_row.t;
    row.FinalResidualInf = final_row.ResidualInf;
    row.FinalGridL2 = numeric_or_nan(final_row, 'GridL2Indicator');
    row.FinalFDH1 = numeric_or_nan(final_row, 'FDH1Indicator');
    row.FinalFDH2 = numeric_or_nan(final_row, 'FDH2Indicator');
    row.FinalJacobianCond = final_row.JacobianCond;
    row.FinalPSDRatio = final_row.HessianPSDRatio;
    row.FinalIndefRatio = final_row.HessianIndefRatio;
    row.ReachedTEnd = abs(row.FinalT) <= 1e-12;
    row.Success = row.ReachedTEnd;
    [row.Suitability, row.Comment] = classify_case(row, spec);
end

function value = numeric_or_nan(tbl_row, name)
    if any(strcmp(tbl_row.Properties.VariableNames, name))
        value = tbl_row.(name);
        if isempty(value)
            value = NaN;
        end
    else
        value = NaN;
    end
end

function [label, comment] = classify_case(row, spec)
    if ~row.Success
        label = "not suitable yet";
        comment = sprintf('%s case did not reach t = 0 under the current settings.', spec.difficulty);
        return;
    end

    if row.FinalPSDRatio >= 0.995 && (isnan(row.FinalGridL2) || row.FinalGridL2 <= 1e-8)
        label = "well suited";
        comment = 'Continuation reaches t = 0 cleanly with strong convexity diagnostics.';
        return;
    end

    if row.FinalPSDRatio >= 0.90
        label = "usable but weaker";
        comment = 'Solver reaches t = 0, but convexity/accuracy diagnostics are noticeably weaker.';
        return;
    end

    label = "borderline";
    comment = 'Solver reaches t = 0, but branch quality is weak and needs caution.';
end

function write_markdown_summary(summary_table, output_path)
    fid = fopen(output_path, 'w');
    if fid < 0
        error('Could not open %s for writing.', output_path);
    end
    cleaner = onCleanup(@() fclose(fid));

    fprintf(fid, '# u0-anchor case summary\n\n');
    fprintf(fid, '| Case | Family | Difficulty | Success | Final t | Residual inf | GridL2 | PSD ratio | Suitability |\n');
    fprintf(fid, '| --- | --- | --- | --- | ---: | ---: | ---: | ---: | --- |\n');

    for k = 1:height(summary_table)
        fprintf(fid, '| %s | %s | %s | %s | %.5g | %.3e | %s | %.3f | %s |\n', ...
            textify(summary_table.CaseName(k)), ...
            textify(summary_table.Family(k)), ...
            textify(summary_table.Difficulty(k)), ...
            logical_word(summary_table.Success(k)), ...
            summary_table.FinalT(k), ...
            summary_table.FinalResidualInf(k), ...
            format_optional(summary_table.FinalGridL2(k)), ...
            summary_table.FinalPSDRatio(k), ...
            textify(summary_table.Suitability(k)));
    end

    fprintf(fid, '\n## Case notes\n\n');
    for k = 1:height(summary_table)
        fprintf(fid, '- `%s`: %s Solver mode: %s. %s\n', ...
            textify(summary_table.CaseName(k)), ...
            textify(summary_table.SolutionCharacter(k)), ...
            textify(summary_table.SolverMode(k)), ...
            textify(summary_table.Comment(k)));
    end
end

function text = format_optional(value)
    if isnan(value)
        text = 'n/a';
    else
        text = sprintf('%.3e', value);
    end
end

function text = logical_word(tf)
    if tf
        text = 'true';
    else
        text = 'false';
    end
end

function out = textify(value)
    if iscell(value)
        value = value{1};
    end
    if isstring(value)
        out = char(value);
    else
        out = value;
    end
end
