function u0_anchor_case_gallery_n_sweep_demo()
% Batch paired-(N,p) sweeps for the examples included in u0_anchor_case_gallery.
%
% This script regenerates the error-vs-N plots used by the gallery PDF.

    cases = { ...
        'paper_example_5_1', ...
        'mild_exp_separable', ...
        'mixed_polynomial_convex', ...
        'mild_sextic_convex', ...
        'gaussian_bump_convex', ...
        'quartic_convex'};

    sweep_options = struct( ...
        'N_values', [2, 4:2:32], ...
        'p_values', [3, 5:2:33], ...
        'run_tag', 'gallery_cn_contnorm_tables_paired_p_to_32', ...
        'show_figures', false);

    for k = 1:numel(cases)
        case_name = cases{k};
        fprintf('\n===== GALLERY N-SWEEP CASE %s =====\n', case_name);
        u0_anchor_monge_ampere_homotopy_demo(case_name, sweep_options);
    end
end
