function [inventory_table, inventory_states] = research_load_terminal_state_inventory(manifest)
%RESEARCH_LOAD_TERMINAL_STATE_INVENTORY Load successful terminal states.

    if isempty(manifest)
        inventory_table = manifest([], :);
        inventory_states = cell(0, 1);
        return;
    end

    required_paths = isfile(cellstr(manifest.TerminalStatePath)) ...
        & isfile(cellstr(manifest.TerminalMetricsPath));
    valid_rows = manifest.Success & manifest.ReachedTEnd & required_paths;
    selected = manifest(valid_rows, :);

    num_rows = height(selected);
    rows = repmat(empty_inventory_row(), num_rows, 1);
    inventory_states = cell(num_rows, 1);

    for k = 1:num_rows
        state = load(selected.TerminalStatePath{k});
        metrics = readtable(selected.TerminalMetricsPath{k}, 'TextType', 'string', ...
            'VariableNamingRule', 'preserve');

        rows(k).CaseName = selected.CaseName(k);
        rows(k).ExperimentTag = selected.ExperimentTag(k);
        rows(k).AnchorTag = selected.AnchorTag(k);
        rows(k).AnchorFamily = selected.AnchorFamily(k);
        rows(k).AnchorLabel = selected.AnchorLabel(k);
        rows(k).RunTag = selected.RunTag(k);
        rows(k).RunDirectory = selected.RunDirectory(k);
        rows(k).AcceptancePolicy = selected.AcceptancePolicy(k);
        rows(k).ConvexityMode = selected.ConvexityMode(k);
        rows(k).LineSearchFallbackEnabled = selected.LineSearchFallbackEnabled(k);
        rows(k).Success = selected.Success(k);
        rows(k).ReachedTEnd = selected.ReachedTEnd(k);
        rows(k).FinalT = state.t_final;
        rows(k).FinalResidualInf = state.residual_final;
        rows(k).FinalJacobianCond = state.jacobian_cond_final;
        rows(k).FinalPSDRatio = state.psd_ratio_final;
        rows(k).FinalIndefRatio = state.indef_ratio_final;
        rows(k).CoefficientCount = numel(state.U_final);
        rows(k).GridShape = string(sprintf('%dx%d', size(state.u_num_eval, 1), size(state.u_num_eval, 2)));
        rows(k).EvalPoints = metrics.EvalPoints(1);
        rows(k).TerminalStatePath = selected.TerminalStatePath(k);
        rows(k).TerminalMetricsPath = selected.TerminalMetricsPath(k);

        inventory_states{k} = state;
    end

    inventory_table = struct2table(rows);
end

function row = empty_inventory_row()
    row = struct( ...
        'CaseName', "", ...
        'ExperimentTag', "", ...
        'AnchorTag', "", ...
        'AnchorFamily', "", ...
        'AnchorLabel', "", ...
        'RunTag', "", ...
        'RunDirectory', "", ...
        'AcceptancePolicy', "", ...
        'ConvexityMode', "", ...
        'LineSearchFallbackEnabled', false, ...
        'Success', false, ...
        'ReachedTEnd', false, ...
        'FinalT', NaN, ...
        'FinalResidualInf', NaN, ...
        'FinalJacobianCond', NaN, ...
        'FinalPSDRatio', NaN, ...
        'FinalIndefRatio', NaN, ...
        'CoefficientCount', NaN, ...
        'GridShape', "", ...
        'EvalPoints', NaN, ...
        'TerminalStatePath', "", ...
        'TerminalMetricsPath', "");
end
